# Generated by Django 5.1.4 on 2024-12-11 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprendedores.emprendedor')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprendedores.evento')),
            ],
            options={
                'unique_together': {('emprendedor', 'evento')},
            },
        ),
    ]
