# Generated by Django 5.1.4 on 2024-12-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedores', '0002_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoria',
            name='duracion_horas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (horas)'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (horas)'),
        ),
    ]
