# Generated by Django 5.1.4 on 2024-12-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedores', '0002_alter_emprendedor_rango_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='orientacion_sexual',
            field=models.CharField(blank=True, choices=[('H', 'Heterosexual'), ('B', 'Bisexual'), ('G', 'Gay'), ('O', 'Otro')], max_length=50, null=True),
        ),
    ]
