# Generated by Django 5.1.4 on 2024-12-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedores', '0003_alter_asesoria_duracion_horas_alter_taller_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadocampesino',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
