# Generated by Django 5.1.4 on 2024-12-11 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('emprendedores', '0004_evento_asesoria_mercadocampesino_taller_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='objeto_id',
            field=models.PositiveIntegerField(verbose_name='ID del Evento'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='tipo_evento',
            field=models.ForeignKey(limit_choices_to={'model__in': ('asesoria', 'taller', 'mercadocampesino')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Evento'),
        ),
    ]
