# Generated by Django 5.1.4 on 2024-12-11 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedores', '0007_alter_mercadocampesino_total_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadocampesino',
            name='total_venta',
            field=models.IntegerField(help_text='Ingrese el total de ventas con puntos como separadores de miles (ej. 3.000.000)', validators=[django.core.validators.RegexValidator(code='invalid_number', message='Ingrese un número válido con puntos como separadores de miles.', regex='^\\d{1,3}(\\.\\d{3})*$')]),
        ),
    ]
