# Generated by Django 5.1.4 on 2024-12-11 18:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedores', '0008_alter_mercadocampesino_total_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercadocampesino',
            name='total_venta',
        ),
        migrations.CreateModel(
            name='VentaEmprendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_venta', models.DecimalField(decimal_places=2, help_text='Ingrese el monto de la venta sin separadores de miles', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprendedores.emprendedor')),
                ('mercado_campesino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprendedores.mercadocampesino')),
            ],
            options={
                'verbose_name': 'Venta de Emprendedor',
                'verbose_name_plural': 'Ventas de Emprendedores',
                'unique_together': {('emprendedor', 'mercado_campesino')},
            },
        ),
    ]
